# The Docker image that will be used to build your app
image: portfolio

pages:
    stages: deploy
    script:
        - echo "The site will be deploy to $CI_PAGES_URL"
    artifacts:
        paths:
            - portfolio
    rules:
        - if $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH
